# Generated by Django 2.0.6 on 2018-09-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonorDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.CharField(blank=True, max_length=255, null=True)),
                ('person', models.CharField(blank=True, max_length=255, null=True)),
                ('person_contact_number', models.CharField(blank=True, max_length=16, null=True)),
                ('single_donor_address', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('reg_document', models.FileField(upload_to='masters.content_file_name_donor')),
                ('due_amount', models.IntegerField(blank=True, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_swift_code', models.CharField(blank=True, max_length=50, null=True)),
                ('donor_bank_address', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'permissions': (('can_view_scholarship', 'can view scholarship'), ('can_view_student_selection', 'can view student selection'), ('can_view_reports', 'can view reports'), ('can_view_student_reports', 'can view student reports'), ('can_view_app_progress_history', 'can view app progress history'), ('can_view_payments_reports', 'can view payments reports'), ('can_view_my_payments', 'can view my payments'), ('can_view_student_receipts', 'can view student receipts')),
                'ordering': ('user__first_name',),
            },
        ),
    ]
