# Generated by Django 2.0.6 on 2018-09-25 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donor', '0001_initial'),
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donordetails',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='donor_address_rel', to='masters.AddressDetails'),
        ),
        migrations.AddField(
            model_name='donordetails',
            name='bank_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='donor_bank_address_rel', to='masters.AddressDetails'),
        ),
        migrations.AddField(
            model_name='donordetails',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='donor_country_rel', to='masters.CountryDetails'),
        ),
        migrations.AddField(
            model_name='donordetails',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='donor_user_rel', to=settings.AUTH_USER_MODEL),
        ),
    ]
