# Generated by Django 2.0.6 on 2018-09-25 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donor', '0002_auto_20180925_1339'),
        ('student', '0001_initial'),
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdonormapping',
            name='applicant_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='donor_applicant_rel', to='student.ApplicationDetails'),
        ),
        migrations.AddField(
            model_name='studentdonormapping',
            name='donor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='donor_student_rel', to='donor.DonorDetails'),
        ),
        migrations.AddField(
            model_name='studentdonormapping',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_donor_rel', to='student.StudentDetails'),
        ),
        migrations.AddField(
            model_name='programdetails',
            name='degree_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='program_degree_type_rel', to='masters.DegreeTypeDetails'),
        ),
        migrations.AddField(
            model_name='programdetails',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='program_university_rel', to='masters.UniversityDetails'),
        ),
        migrations.AddField(
            model_name='moduledetails',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='module_country_rel', to='masters.CountryDetails'),
        ),
        migrations.AddField(
            model_name='masterandphdformula',
            name='degree_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_phd_formula_degree_type_relation', to='masters.DegreeTypeDetails'),
        ),
        migrations.AddField(
            model_name='masterandphdformula',
            name='scholarship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='phd_scholarship_formula_relation', to='masters.ScholarshipDetails'),
        ),
        migrations.AddField(
            model_name='masterandcourseformula',
            name='degree_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_course_formula_degree_type_relation', to='masters.DegreeTypeDetails'),
        ),
        migrations.AddField(
            model_name='masterandcourseformula',
            name='scholarship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_scholarship_formula_relation', to='masters.ScholarshipDetails'),
        ),
        migrations.AddField(
            model_name='guardianstudentmapping',
            name='guardian',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gurd_std_mapping_rel', to='masters.GuardianDetails'),
        ),
        migrations.AddField(
            model_name='guardianstudentmapping',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='std_gurd_mapping_rel', to='student.StudentDetails'),
        ),
        migrations.AddField(
            model_name='guardiandetails',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guardian_address_rel', to='masters.AddressDetails'),
        ),
        migrations.AddField(
            model_name='guardiandetails',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guardian_user_rel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='developmentprogram',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='development_module_rel', to='masters.ModuleDetails'),
        ),
        migrations.AddField(
            model_name='developmentprogram',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='development_semester_rel', to='masters.SemesterDetails'),
        ),
        migrations.AddField(
            model_name='developmentprogram',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='development_year_rel', to='masters.YearDetails'),
        ),
        migrations.AddField(
            model_name='degreeformula',
            name='degree_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='degree_formula_degree_type_relation', to='masters.DegreeTypeDetails'),
        ),
        migrations.AddField(
            model_name='degreeformula',
            name='scholarship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='degree_scholarship_formula_relation', to='masters.ScholarshipDetails'),
        ),
        migrations.AddField(
            model_name='degreedetails',
            name='degree_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='degree_degree_type_rel', to='masters.DegreeTypeDetails'),
        ),
        migrations.AddField(
            model_name='addressdetails',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='address_country_rel', to='masters.CountryDetails'),
        ),
    ]
