# Generated by Django 2.0.6 on 2018-07-03 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masters', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdonormapping',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_donor_rel', to='student.StudentDetails'),
        ),
        migrations.AddField(
            model_name='programdetails',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='program_country_rel', to='masters.CountryDetails'),
        ),
        migrations.AddField(
            model_name='programdetails',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='program_university_rel', to='masters.UniversityDetails'),
        ),
        migrations.AddField(
            model_name='partnerdetails',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partner_address_rel', to='masters.AddressDetails'),
        ),
        migrations.AddField(
            model_name='partnerdetails',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partner_country_rel', to='masters.CountryDetails'),
        ),
        migrations.AddField(
            model_name='partnerdetails',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partner_user_rel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moduledetails',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='module_country_rel', to='masters.CountryDetails'),
        ),
        migrations.AddField(
            model_name='masterandphdformula',
            name='scholarship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='phd_scholarship_formula_relation', to='masters.ScholarshipDetails'),
        ),
        migrations.AddField(
            model_name='masterandcourseformula',
            name='scholarship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_scholarship_formula_relation', to='masters.ScholarshipDetails'),
        ),
        migrations.AddField(
            model_name='guardianstudentmapping',
            name='guardian',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gurd_std_mapping_rel', to='masters.GuardianDetails'),
        ),
        migrations.AddField(
            model_name='guardianstudentmapping',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='std_gurd_mapping_rel', to='student.StudentDetails'),
        ),
        migrations.AddField(
            model_name='guardiandetails',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guardian_address_rel', to='masters.AddressDetails'),
        ),
        migrations.AddField(
            model_name='guardiandetails',
            name='nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guardian_nationality_rel', to='masters.CountryDetails'),
        ),
        migrations.AddField(
            model_name='donordetails',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='donor_address_rel', to='masters.AddressDetails'),
        ),
        migrations.AddField(
            model_name='donordetails',
            name='bank_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='donor_bank_address_rel', to='masters.AddressDetails'),
        ),
        migrations.AddField(
            model_name='donordetails',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='donor_country_rel', to='masters.CountryDetails'),
        ),
        migrations.AddField(
            model_name='donordetails',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='donor_user_rel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='developmentprogram',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='development_module_rel', to='masters.ModuleDetails'),
        ),
        migrations.AddField(
            model_name='developmentprogram',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='development_semester_rel', to='masters.SemesterDetails'),
        ),
        migrations.AddField(
            model_name='developmentprogram',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='development_year_rel', to='masters.YearDetails'),
        ),
        migrations.AddField(
            model_name='degreeformula',
            name='scholarship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='degree_scholarship_formula_relation', to='masters.ScholarshipDetails'),
        ),
        migrations.AddField(
            model_name='addressdetails',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='address_country_rel', to='masters.CountryDetails'),
        ),
    ]
