# Generated by Django 2.0.6 on 2018-07-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_auto_20180703_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donordetails',
            name='due_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
