# Generated by Django 2.0.6 on 2019-05-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_auto_20181015_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadTermCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('term_condition', models.FileField(blank=True, null=True, upload_to='term_condition/pdf')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
