# Generated by Django 2.0.6 on 2018-07-05 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_auto_20180703_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degreedetails',
            name='degree_type',
        ),
    ]
