# Generated by Django 2.0.6 on 2019-06-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_uploadtermcondition'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftSkillDevelopmentProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('program_name', models.CharField(blank=True, max_length=255, null=True)),
                ('objectives', models.CharField(blank=True, max_length=2000, null=True)),
                ('delivery_method', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_location', models.CharField(blank=True, max_length=256, null=True)),
                ('organizer', models.CharField(blank=True, max_length=256, null=True)),
                ('delivery_date', models.DateField(null=True)),
                ('completion_deadline', models.DateField(null=True)),
                ('rsvp_method', models.CharField(blank=True, max_length=2000, null=True)),
                ('remarks', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
