# Generated by Django 2.0.6 on 2018-07-05 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_auto_20180705_0516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programdetails',
            name='country',
        ),
    ]
