# Generated by Django 2.0.6 on 2018-07-05 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_remove_programdetails_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programdetails',
            name='degree_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='program_degree_type_rel', to='masters.DegreeTypeDetails'),
        ),
    ]
