# Generated by Django 2.0.6 on 2018-07-06 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_auto_20180705_0622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='developmentprogram',
            old_name='outecomes',
            new_name='outcome',
        ),
    ]
