# Generated by Django 2.0.6 on 2018-07-06 10:30

from django.db import migrations, models
import masters.models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0009_auto_20180706_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerdetails',
            name='single_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='partnerdetails',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=masters.models.content_file_name_partner),
        ),
    ]
