# Generated by Django 2.0.6 on 2018-07-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0010_auto_20180706_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='donordetails',
            name='donor_bank_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='donordetails',
            name='single_donor_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
