# Generated by Django 2.0.6 on 2018-09-25 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import student.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicQualificationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(blank=True, max_length=255, null=True)),
                ('level_year', models.CharField(blank=True, max_length=6, null=True)),
                ('level_result', models.CharField(blank=True, max_length=255, null=True)),
                ('level_institution', models.CharField(blank=True, max_length=255, null=True)),
                ('level_result_document', models.FileField(upload_to=student.models.content_file_name_report)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdminNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('message', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ApplicantAboutDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('about_yourself', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicantAcademicProgressDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('gpa_scored', models.CharField(blank=True, max_length=255, null=True)),
                ('gpa_from', models.CharField(blank=True, max_length=255, null=True)),
                ('cgpa_scored', models.CharField(blank=True, max_length=255, null=True)),
                ('cgpa_from', models.CharField(blank=True, max_length=255, null=True)),
                ('transcript_document', models.FileField(upload_to=student.models.content_file_name_report)),
                ('is_approved', models.BooleanField(default=False)),
                ('result', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ('-created_on',),
            },
        ),
        migrations.CreateModel(
            name='ApplicantAgreementDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('four_parties_agreement_document', models.FileField(upload_to=student.models.content_file_name_report)),
                ('education_loan_agreement_document', models.FileField(upload_to=student.models.content_file_name_report)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicantDevelopmentProgramDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('certificate_document', models.FileField(upload_to=student.models.content_file_name_report)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicantPsychometricTestDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(blank=True, max_length=255, null=True)),
                ('test_result_document', models.FileField(upload_to=student.models.content_file_name_report)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=25, null=True)),
                ('id_number', models.CharField(blank=True, max_length=100, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=100, null=True)),
                ('passport_image', models.FileField(blank=True, null=True, upload_to=student.models.content_file_name_image)),
                ('telephone_hp', models.CharField(blank=True, max_length=16, null=True)),
                ('telephone_home', models.CharField(blank=True, max_length=16, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('image', models.FileField(upload_to=student.models.content_file_name_image)),
                ('wife_name', models.CharField(blank=True, max_length=255, null=True)),
                ('wife_income', models.CharField(blank=True, max_length=10, null=True)),
                ('wife_pay_slip', models.FileField(upload_to=student.models.content_file_name_report)),
                ('wife_nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('wife_occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('wife_telephone_home', models.CharField(blank=True, max_length=16, null=True)),
                ('wife_dob', models.DateField(blank=True, null=True)),
                ('wife_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('father_income', models.CharField(blank=True, max_length=10, null=True)),
                ('father_pay_slip', models.FileField(upload_to=student.models.content_file_name_report)),
                ('father_nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('father_occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('father_telephone_home', models.CharField(blank=True, max_length=16, null=True)),
                ('father_dob', models.DateField(blank=True, null=True)),
                ('father_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_income', models.CharField(blank=True, max_length=10, null=True)),
                ('mother_pay_slip', models.FileField(upload_to=student.models.content_file_name_report)),
                ('mother_nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('mother_occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_telephone_home', models.CharField(blank=True, max_length=16, null=True)),
                ('mother_dob', models.DateField(blank=True, null=True)),
                ('mother_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('application_id', models.CharField(blank=True, max_length=100, null=True)),
                ('first_interview', models.BooleanField(default=False)),
                ('first_interview_attend', models.BooleanField(default=False)),
                ('first_interview_approval', models.BooleanField(default=False)),
                ('psychometric_test', models.BooleanField(default=False)),
                ('second_interview_attend', models.BooleanField(default=False)),
                ('second_interview_approval', models.BooleanField(default=False)),
                ('admin_approval', models.BooleanField(default=False)),
                ('application_rejection', models.BooleanField(default=False)),
                ('is_sponsored', models.BooleanField(default=False)),
                ('scholarship_fee', models.CharField(blank=True, max_length=15, null=True)),
                ('interview_time', models.CharField(blank=True, max_length=30, null=True)),
                ('interview_date', models.CharField(blank=True, max_length=50, null=True)),
                ('interview_venue', models.CharField(blank=True, max_length=500, null=True)),
                ('second_interview_time', models.CharField(blank=True, max_length=30, null=True)),
                ('second_interview_date', models.CharField(blank=True, max_length=50, null=True)),
                ('second_interview_venue', models.CharField(blank=True, max_length=500, null=True)),
                ('personal_info_flag', models.BooleanField(default=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applicant_address_rel', to='masters.AddressDetails')),
                ('nationality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applicant_nationality_rel', to='masters.CountryDetails')),
                ('passport_issue_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='passport_issue_country_rel', to='masters.CountryDetails')),
                ('permanent_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applicant_permanent_address_rel', to='masters.AddressDetails')),
                ('religion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applicant_religion_rel', to='masters.ReligionDetails')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applicant_semester_rel', to='masters.SemesterDetails')),
            ],
            options={
                'ordering': ('-created_on',),
            },
        ),
        migrations.CreateModel(
            name='ApplicationHistoryDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.CharField(blank=True, max_length=1000, null=True)),
                ('applicant_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applicant_history_rel', to='student.ApplicationDetails')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='CurriculumDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('curriculum_name', models.CharField(blank=True, max_length=255, null=True)),
                ('curriculum_year', models.CharField(blank=True, max_length=10, null=True)),
                ('curriculum_result_document', models.FileField(blank=True, null=True, upload_to=student.models.content_file_name_report)),
                ('academic_qualification', models.BooleanField(default=True)),
                ('applicant_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_applicant_rel', to='student.ApplicationDetails')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnglishQualificationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('english_test', models.CharField(blank=True, max_length=255, null=True)),
                ('english_test_year', models.CharField(blank=True, max_length=10, null=True)),
                ('english_test_result', models.CharField(blank=True, max_length=255, null=True)),
                ('english_test_result_document', models.FileField(upload_to=student.models.content_file_name_report)),
                ('english_qualification', models.BooleanField(default=True)),
                ('applicant_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='english_applicant_rel', to='student.ApplicationDetails')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExperienceDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('work_experience', models.CharField(blank=True, max_length=255, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('work_experience_document', models.FileField(upload_to=student.models.content_file_name_report)),
                ('experience_current', models.BooleanField(default=False)),
                ('applicant_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applicant_experience_rel', to='student.ApplicationDetails')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PassingYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('year', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ScholarshipSelectionDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('admission_letter_document', models.FileField(upload_to=student.models.content_aplicant_file_name_report)),
                ('scholarship_selection', models.BooleanField(default=True)),
                ('applicant_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applicant_scholarship_rel', to='student.ApplicationDetails')),
                ('course_applied', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_scholarship_rel', to='masters.ProgramDetails')),
                ('degree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='degree_scholarship_rel', to='masters.DegreeDetails')),
                ('scholarship', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scholarship_selection_rel', to='masters.ScholarshipDetails')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='university_scholarship_rel', to='masters.UniversityDetails')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiblingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('sibling_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sibling_age', models.CharField(blank=True, max_length=5, null=True)),
                ('sibling_status', models.CharField(blank=True, max_length=255, null=True)),
                ('applicant_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sibling_applicant_rel', to='student.ApplicationDetails')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('birth_date', models.DateField(null=True)),
                ('gender', models.CharField(max_length=25, null=True)),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.FileField(upload_to=student.models.content_student_file_name_image)),
                ('is_active', models.BooleanField(default=True)),
                ('religion', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=16, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_address_rel', to='masters.AddressDetails')),
                ('nationality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_nationality_rel', to='masters.CountryDetails')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_user_rel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_view_student_personal_info', 'can view student personal info'), ('can_view_student_family_info', 'can view student family info'), ('can_view_student_academic_qualification', 'can view student academic qualification'), ('can_view_scholarship_selection', 'can view scholarship selection'), ('can_view_my_application', 'can view my application'), ('can_view_student_psychometric_test', 'can view student psychometric test'), ('can_view_student_agreements', 'can view student agreements'), ('can_view_student_development_program', 'can view student development program certificate'), ('can_view_student_academic_progress', 'can view student academic progress'), ('can_view_student_application_progress_history', 'can view student application progress history')),
            },
        ),
        migrations.CreateModel(
            name='StudentNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('message', models.CharField(blank=True, max_length=500, null=True)),
                ('applicant_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applicant_notification_rel', to='student.ApplicationDetails')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='applicationdetails',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_applicant_rel', to='student.StudentDetails'),
        ),
        migrations.AddField(
            model_name='applicationdetails',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applicant_year_rel', to='masters.YearDetails'),
        ),
        migrations.AddField(
            model_name='applicantpsychometrictestdetails',
            name='applicant_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applicant_psychometric_test_rel', to='student.ApplicationDetails'),
        ),
        migrations.AddField(
            model_name='applicantdevelopmentprogramdetails',
            name='applicant_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='development_program_applicant_rel', to='student.ApplicationDetails'),
        ),
        migrations.AddField(
            model_name='applicantdevelopmentprogramdetails',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='development_program_module_rel', to='masters.DevelopmentProgram'),
        ),
        migrations.AddField(
            model_name='applicantagreementdetails',
            name='applicant_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applicant_agreement_rel', to='student.ApplicationDetails'),
        ),
        migrations.AddField(
            model_name='applicantacademicprogressdetails',
            name='applicant_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applicant_progress_rel', to='student.ApplicationDetails'),
        ),
        migrations.AddField(
            model_name='applicantacademicprogressdetails',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applicant_progress_semester_rel', to='masters.SemesterDetails'),
        ),
        migrations.AddField(
            model_name='applicantacademicprogressdetails',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applicant_progress_year_rel', to='masters.YearDetails'),
        ),
        migrations.AddField(
            model_name='applicantaboutdetails',
            name='applicant_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applicant_about_rel', to='student.ApplicationDetails'),
        ),
        migrations.AddField(
            model_name='adminnotifications',
            name='applicant_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_notification_rel', to='student.ApplicationDetails'),
        ),
        migrations.AddField(
            model_name='academicqualificationdetails',
            name='applicant_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='academic_applicant_rel', to='student.ApplicationDetails'),
        ),
    ]
