# Generated by Django 2.0.6 on 2019-03-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20181001_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdetails',
            name='father_home_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicationdetails',
            name='mother_home_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicationdetails',
            name='wife_home_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
