# Generated by Django 2.0.6 on 2019-05-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20190322_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicqualificationdetails',
            name='degree',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='academicqualificationdetails',
            name='major',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='academicqualificationdetails',
            name='other_degree',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
