# Generated by Django 2.0.6 on 2018-09-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonorReceiptVoucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('voucher_number', models.CharField(max_length=50, null=True)),
                ('voucher_amount', models.FloatField(max_length=50, null=True)),
                ('voucher_total', models.FloatField(max_length=50, null=True)),
                ('voucher_description', models.CharField(max_length=50, null=True)),
                ('voucher_type', models.CharField(max_length=50, null=True)),
                ('voucher_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentPaymentReceiptVoucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('voucher_number', models.CharField(max_length=50, null=True)),
                ('voucher_date', models.DateField()),
                ('voucher_amount', models.FloatField(max_length=50, null=True)),
                ('voucher_total', models.FloatField(max_length=50, null=True)),
                ('voucher_description', models.CharField(max_length=50, null=True)),
                ('voucher_beneficiary', models.CharField(max_length=50, null=True)),
                ('voucher_type', models.CharField(max_length=50, null=True)),
            ],
            options={
                'permissions': (('can_view_student_payment_voucher', 'can view student payment voucher'), ('can_view_student_receipt_voucher', 'can view student receipt voucher'), ('can_view_donor_payment_voucher', 'can view donor payment voucher'), ('can_view_donor_receipt_voucher', 'can view donor receipt voucher')),
                'ordering': ('-created_on',),
            },
        ),
    ]
