# Generated by Django 2.0.6 on 2018-09-25 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('student', '0001_initial'),
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpaymentreceiptvoucher',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rel_student_payment_receipt_voucher', to='student.ApplicationDetails'),
        ),
        migrations.AddField(
            model_name='donorreceiptvoucher',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rel_donor_receipt_voucher', to='student.ApplicationDetails'),
        ),
        migrations.AddField(
            model_name='donorreceiptvoucher',
            name='donor_student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rel_donor_student_receipt_voucher', to='masters.StudentDonorMapping'),
        ),
    ]
