# Generated by Django 2.0.6 on 2018-10-18 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20180925_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentpaymentreceiptvoucher',
            options={'ordering': ('-created_on',), 'permissions': (('can_view_student_payment_voucher', 'can view student payment voucher'), ('can_view_student_receipt_voucher', 'can view student receipt voucher'), ('can_view_donor_payment_voucher', 'can view donor payment voucher'), ('can_view_donor_receipt_voucher', 'can view donor receipt voucher'), ('can_view_student_report', 'can view student report'), ('can_view_student_repayment_report', 'can view student repayment report'), ('can_view_donor_report', 'can view donor report'), ('can_view_student_reciept_payment_voucher', 'can_view_student_reciept_payment_voucher'), ('can_view_approve_and_paid_total', 'can view approve and paid total'))},
        ),
    ]
