# Generated by Django 2.0.6 on 2018-09-25 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import partner.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('masters', '0002_auto_20180925_1339'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('office_name', models.CharField(blank=True, max_length=255, null=True)),
                ('person_one', models.CharField(blank=True, max_length=100, null=True)),
                ('person_one_contact_number', models.CharField(blank=True, max_length=16, null=True)),
                ('person_two', models.CharField(blank=True, max_length=100, null=True)),
                ('person_two_contact_number', models.CharField(blank=True, max_length=16, null=True)),
                ('office_contact_number', models.CharField(blank=True, max_length=16, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('single_address', models.CharField(blank=True, max_length=500, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to=partner.models.content_file_name_partner)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partner_address_rel', to='masters.AddressDetails')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partner_country_rel', to='masters.CountryDetails')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partner_user_rel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_view_applicant_details', 'can view applicant details'), ('can_view_applicant_scholarship', 'can view applicant scholarship'), ('can_view_approving_application', 'can view approving application'), ('can_view_progress_history', 'can view progress history'), ('can_view_psychometric_test_report', 'can view psychometric test report'), ('can_view_link_student_program', 'can view link student program'), ('can_view_academic_progress', 'can view academic progress'), ('can_view_attendance_report', 'can view attendance report'), ('can_view_accepted_students', 'can view accepted students'), ('can_view_student_agreement', 'can view student agreement'), ('can_view_semester_result', 'can view semester result')),
                'ordering': ('user__first_name',),
            },
        ),
        migrations.CreateModel(
            name='StudentModuleMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('applicant_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applicant_module_rel', to='student.ApplicationDetails')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_module_country_rel', to='masters.CountryDetails')),
                ('degree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='degree_module_rel', to='masters.DegreeDetails')),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_module_link_rel', to='masters.DevelopmentProgram')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='program_module_rel', to='masters.ProgramDetails')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
