# Generated by Django 2.0.6 on 2019-06-14 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_softskilldevelopmentprogram'),
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodulemapping',
            name='soft_skill_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='soft_skill_prog_rel', to='masters.SoftSkillDevelopmentProgram'),
        ),
    ]
